<%@ Page Language="vb" AutoEventWireup="false" CodeBehind="Baja_usuario.aspx.vb" Inherits="Proyecto_Final_GrupoZon.Baja_usuario" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <h1>Baja de usuarios</h1>

            <br />

            <asp:GridView ID="grdviewUsuarios" runat="server" AutoGenerateDeleteButton="True"></asp:GridView>
        </div>
        
    </form>
</body>
</html>
