<%@ Page Language="vb" AutoEventWireup="false" CodeBehind="clientes_listado.aspx.vb" Inherits="Proyecto_Final_GrupoZon.clientes_listado" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
           <h1>Clientes</h1>

            <br />

            <asp:GridView ID="grdviewClientes" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True"></asp:GridView>
            
            <br />

            <asp:Button ID="btnAlta" runat="server" Text="Altas de clientes" />
        </div>
    </form>
</body>
</html>
