<%@ Page Language="vb" AutoEventWireup="false" CodeBehind="Listado_usuarios.aspx.vb" Inherits="Proyecto_Final_GrupoZon.Listado_usuarios" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <h1>Usuarios</h1>

            <br />

            <asp:GridView ID="grdviewUsuarios" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True"></asp:GridView>
            
            <br />

            <asp:Button ID="btnAlta" runat="server" Text="Altas de usuarios" />
        </div>
        
    </form>
</body>
</html>
