<%@ Page Language="vb" AutoEventWireup="false" CodeBehind="proyecto_listado.aspx.vb" Inherits="Proyecto_Final_GrupoZon.proyecto_listado" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link href="Content/estilos_proyecto_listado.css" rel="stylesheet" />
    <link href="Content/bootstrap.min.css" rel="stylesheet" />
    <link href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" rel="stylesheet" />

    <title></title>
</head>

<body>

    <form id="form1" runat="server">
     <header>
            <nav>
               <div class="menu-icon">
                  <i class="fa fa-bars fa-2x"></i>
               </div>
               <div class="logo">
                  <img src="img/logo%20pez%20fondo%20oscuro.png" class="pez" />
               </div>
               <div class="menu">
                  <ul>
                     <li><a href="calendario.aspx">Calendario</a></li>
                     <li><a href="#">Gestion Proyectos</a></li>
                     <li><a href="#">Gestion Usuarios</a></li>
                  </ul>
               </div>
            </nav>
    </header>



        <div class="padre">
            <div class="hijo">
                <div class="grid">
                    <h1>Listado</h1>
                </div>

                <div class="grid">
                    <asp:GridView ID="gridProyecto" runat="server" class="table" HeaderStyle-CssClass="thead-dark" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
                        <Columns>
                            <asp:TemplateField>
                                <ItemTemplate>
                                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal" id="myModal">
                                      Launch demo modal
                                    </button>
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                        
                    </asp:GridView>

                </div>

                <div class="grid">
                    <asp:Button ID="btnAlta" runat="server" Text="Button" CssClass="btn btn-dark" />
                </div>                                 

                
            </div>
            
            
        </div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>


    </form>

        
</body>
    <script src="Scripts/bootstrap.min.js"></script>
    <script src="Scripts/jquery-3.3.1.min.js"></script>

    <script>
        $('#myModal').on('shown.bs.modal', function () {
      $('#modal').trigger('focus')
    })
    </script>

    <script>
     $(document).ready(function() {
                $(".menu-icon").on("click", function() {
                      $("nav ul").toggleClass("showing");
                });
          });

          // Scrolling Effect

          $(window).on("scroll", function() {
                if($(window).scrollTop()) {
                      $('nav').addClass('black');
                }

                else {
                      $('nav').removeClass('black');
                }
          })
    </script>
</html>
