<%@ Page Language="vb" AutoEventWireup="false" CodeBehind="usuario_listado.aspx.vb" Inherits="Proyecto_Final_GrupoZon.usuario_listado" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link href="Content/estilos_listado.css" rel="stylesheet" />
    <link href="Content/bootstrap.min.css" rel="stylesheet" />
    <link href="Content/nav.css" rel="stylesheet" />
    <link href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" rel="stylesheet" />
    <title>Usuarios Listado</title>
</head>
<body>
    <form id="form1" runat="server">
        <header>
                <nav>
                   <div class="menu-icon">
                      <i class="fa fa-bars fa-2x"></i>
                   </div>
                   <div class="logo">
                      <img src="img/logo%20pez%20fondo%20oscuro.png" class="pez" />
                   </div>
                   <div class="menu">
                      <ul>
                         <li><a href="calendario.aspx">Calendario</a></li>
                         <li><a href="proyecto_listado.aspx">Gestion Proyectos</a></li>
                         <li><a href="usuario_listado.aspx">Gestion Usuarios</a></li>
                      </ul>
                   </div>
                </nav>
        </header>

        <div class="padre">
            <div class="hijo">
                <div class="grid">
                    <h1>Usuarios</h1>
                </div>

                <div class="grid">
                    <asp:GridView ID="grdviewUsuarios" runat="server" class="table" HeaderStyle-CssClass="thead-dark" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True"></asp:GridView>
                </div>

                <div class="grid">
                    <asp:Button ID="btnAlta" runat="server" Text="Altas de usuarios" CssClass="btn btn-dark" />
                </div>
            </div>
        </div>
        
    </form>
</body>
</html>
