<%@ Page Language="vb" AutoEventWireup="false" CodeBehind="usuario_listado.aspx.vb" Inherits="Proyecto_Final_GrupoZon.usuario_listado" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link href="Content/estilos_proyecto.css" rel="stylesheet" />
    <link href="Content/bootstrap.min.css" rel="stylesheet" />
    <script src="Scripts/bootstrap.min.js"></script>
    <title>Listado usuarios</title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <div>
                <h1>Usuarios</h1>
            </div>

            <div>
                <asp:Label ID="Label2" runat="server" Text="Criterio:"></asp:Label>
                <asp:DropDownList ID="dropDownCriterios" runat="server" AutoPostBack="True"></asp:DropDownList>
                <asp:Label ID="Label3" runat="server" Text="Filtro:"></asp:Label>
                <asp:TextBox ID="txtFiltro" runat="server"></asp:TextBox>
                <asp:Button ID="btnFiltrar" runat="server" Text="Aplicar filtro" />
            </div>
            
            <div>
                <asp:Label ID="Label1" runat="server" Text="Filtros:"></asp:Label>
                <asp:Label ID="lblFiltros" runat="server" Text="No hay filtros establecidos."></asp:Label>
                <asp:Button ID="btnEliminarFiltros" runat="server" Font-Size="Smaller" Text="X" Visible="False" />
            </div>
            

            <div>
                <asp:GridView ID="grdviewUsuarios" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CssClass="table">
                    <HeaderStyle CssClass="thead-dark" />
                </asp:GridView>
            </div>


            <div>
                <asp:Button ID="btnAlta" runat="server" Text="Altas de usuarios" />
            </div>
            
        </div>
        
        <asp:Label ID="lblQuery" runat="server" Text="Label"></asp:Label>
        
    </form>
</body>
</html>
